### ISSUE TITLE
Spawning sometimes still immediately results in death

### ISSUE THREAD

**Issue by cmaines** [bucketon/OWRandomSpeedrun#68] opened 2023-02-19 08:09 UTC
Happened a few times, including for the Southern Observatory spawn.

**Comment by cmaines** [comment] 2023-02-19 08:11
Maybe related to #69? Not sure.

**Comment by bucketon** [comment] 2023-02-19 22:18
duplicate of https://github.com/bucketon/OWRandomSpeedrun/issues/69 as far as I can tell

**Comment by bucketon** [comment] 2023-02-19 22:25
oh oops my log was causing an identical NRE, reopening

**Closed as completed** 2023-02-21 07:49 UTC
